apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::963801344255:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-S7OJ1ZZ4XFRX
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::963801344255:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-11-13T20:53:16Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1680"
  uid: 248a9fe8-f63b-4005-ab36-653764fe05b6
